### ISSUE TITLE
I Want to help

### ISSUE THREAD

**Issue by ErickRock** [Iwuh/Wycademy#1]
Where do you get the monsters information to add to the Json file?

I want to help by increasing the list of monsters and translating some of the content to PT-BR

**Comment by Iwuh** [comment]
The way the monster data is structured at the moment is pretty messed up. The data is [here](https://github.com/Iwuh/Wycademy/blob/rewrite/WycademyV2/src/WycademyV2/Data/Monster%20Info.xlsx) and the python script to convert it to json is [here](https://github.com/Iwuh/Wycademy/blob/rewrite/WycademyV2/src/WycademyV2/Data/generatemonsterinfo.py). All the spreadsheet is in English, though. You can try your hand at translating, and we'll see from there about monster data in other languages.
